### ISSUE TITLE
Prevent warnings because of accessing undefined variables/array keys (?)

### ISSUE THREAD

**Issue by YakovL** [YakovL/MainTiddlyServer#10]
[Inception](https://groups.google.com/g/tiddlywikiclassic/c/je0XR_w0vmc); TODO: get enough details to reproduce and fix.

Some of the issues to deal with:

- [x] add `global $debug_mode;` to `updateTW` (not exactly this issue, but still)
- [x] `chooseWorkingFolder`: use `if(isset(self::$options['dataFolders'][$name]))` instead of `if(self::$options['dataFolders'][$name])`
- [x] check `isset($_POST['backupid'])` before using `$_POST['backupid']`
- [x] fix `removeInjectedJsFromWiki`: `$wikiData` should be `$content` (wasn't working before, but it is a safeguard for an edge case when the same code is inside the storeArea)
- [x] in `updateTW`, make "safe" checks for `$tiddlerChange->added`, `$tiddlerChange->changed`, `$tiddlerChange->renamed`, `$changes->title`, `$changes->markupBlocks`
- [x] fix `getImageByUriAndSave` draft: `if($isBase64)`, calc `$data` from `$url` (currently `$data` is an unassigned variable)
- [x] `Options::get`: use `isset` before returning (return `null` otherwise; have to deal with defaults consistently)
- [x] similarly, update `setOption`; and make sure that "different empty values" won't trigger a redundant options saving
- [x] the `if(Options::chooseWorkingFolder($requestedFolderName) != $requestedFolder)` check: `$requestedFolder` should be `$requestedFolderName`
- [x] use `isset` in `Options::load`
- [x] use `isset` for `$requestedUrlParts['port']`, `$requestedUrlParts['query']`
  - may want to use bits like `parse_url($requestedUrl, PHP_URL_PORT)` instead
- [x] wrap `$_POST['wiki']`/`$_REQUEST['wiki']` before `?` with `isset`
- [x] review the [suggestion](#issuecomment-1951462308) to use `LIBXML_NOERROR` → #11
- [x] optionally, check `$_POST['backupFolder']` with `isset` (frontend always passes a value, though)
- test main features with `error_reporting(E_ALL);`:
  - [x] open a TW
  - [x] saving (non-granulated)
  - [x] saving (granulated)
    - [x] deleting a tiddler (at some point, no POST request was sent, with granulated saving)
  - [x] saving a backup
  - [x] TW list page
  - [x] options page
  - [x] saving an option
  - [x] cold start (w/o options file)
  - [x] proxying (for instance, for EEP)
    - [ ] test with a url without `path` (done already: no `query`, no `port`)
- [ ] find a good linter/static analyser that will show as many of these errors as possible (initially, [for 2996d87](https://github.com/YakovL/MainTiddlyServer/blob/2996d87175edba0b6aef7882f0f381dc4d669edc/index.php))
  - IntelePhense [claims](https://github.com/bmewburn/vscode-intelephense/issues/1638) to find "undefined property" issues, but doesn't seem to do so in my first test
  - [ ] see PHPStan, Psalm, Phan[*](https://github.com/index0h/php-conventions/issues/49), Exakat; ideally, in a VS Code plugin, not requiring anything else to install
  - presumably, some other `Options`' methods should be updated (`init`, `getWorkingFolder` – use `isset`? may be also refactor `chooseWorkingFolder`)
  - also, learn more about [type declaration](https://www.php.net/manual/en/language.types.declarations.php) (how close can we get to TS)
- [ ] (may be cover some of the scenarios with autotests?)

**Comment by visick** [comment]
Issue is:
- PHP previously reported errors at the E_NOTICE level if a variable or array key that had not previously been given a value was used, such as to test for its existence--e.g. `if($myvar)` {...} will throw the error if `$myvar` hasn't already been defined.
- PHP 8+ elevates this to E_WARNING errors, and in most default configurations, warnings will be echoed to the document
- This error is slated to be elevated to E_ERROR in future versions, which will stop execution
- MTS has a number of occurrences of this error

How to reproduce:
- Using MTS to run a TW on a server running PHP 8+ should cause the errors to be displayed in the document and logged in error.log.
- On earlier versions of PHP, the errors should be shown if `error_reporting(E_ALL);` is added to the top of index.php

See attached screenshot for an example. This test file was running under PHP 7.3 (I think), so I used error_reporting to show the errors. Some errors kick in when loading the wiki, others (as shown here) when saving it.

How to fix:
Depends a little on how the undefined variable/key is used; in simple cases, replacing `if($myvar) {...}` with `if(isset($myvar)) {...}` will take care of the problem.
 
![mtserrors](https://github.com/YakovL/MainTiddlyServer/assets/13279590/c2e77f4d-8fe1-4c50-a459-af6eed6c1d67)

**Comment by YakovL** [comment]
Hi, @visick, could you retest with the current dev snapshot? I expect only the `$requestedFolder` issue to be left, but I can see some warnings on your side that I don't reproduce yet (see the screenshot bits that I've extracted from your screen – in the issue description). If there are additional warnings, please share them as a text (not as just an image)

**Comment by YakovL** [comment]
No more warnings on my side (I may have missed some case, though). @visick could you retest (use the `dev` branch)?

See also the issue description for details

**Comment by visick** [comment]
I get no warnings in opening a TW, thanks!

When I open a TW and then save it, however, I still see warnings that appear in the message area of the TW:

```
Error while saving. Server:
Warning: Undefined array key "wiki" in /(path)/index.php on line 1363
Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 1 in /(path)/index.php on line 1202

```

**Comment by YakovL** [comment]
Hi @visick , I've fixed the first warning, but the second one seems to be of a different nature (most probably related to your TW content). Please try it with a different TW file; in my experience, this happened with a) some special characters in TW content that were not converted into `&something;` or `&#123;` and b) some bad field name(s) (I don't remember the details, but it was probably some kind of bad editing of html via a text editor).

Note also that you haven't this warning initailly, so this should be from a recent change. If saving works fine with another TW, you may want to try editing your main TW in a text editor (hm, looks like the problem is on the `line: 1` on your TW html, that's strange), and if you succeed with fixing that, you should also try to edit it via MTS and check if the problem comes back. Could it be that you got a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) in your TW file?

**Comment by visick** [comment]
Thank you, Yakov; working great for me now, no warnings.
You were right, I accidentally introduced the second error by adding error_reporting to index.php.

**Comment by visick** [comment]
Actually, let me amend that. I'm still getting the `DOMDocument::loadHTML()` warning with an empty TW (2.10.0), though it doesn't actually prevent saving from occurring.

I dug into this a little more and found that `DOMDocument::loadHTML()` uses an HTML 4 parser and differences in HTML 5 can cause it to report errors: [https://www.php.net/manual/en/domdocument.loadhtml.php](https://www.php.net/manual/en/domdocument.loadhtml.php)

As suggested on that page, I added `LIBXML_NOERROR` to line 1202 in MTS index.php to give HTML 5 compatibility:

`$doc = new DOMDocument(); $doc->LoadHTML('<html><body>'.$tiddlerText.'</body></html>', LIBXML_NOERROR);`

That got rid of the warning and all is working fine now when the TW is saved.

Thanks!

**Comment by YakovL** [comment]
Closing this in favor of #11

**Comment by YakovL** [comment]
@visick could you help with reproducibility of #11 ?
